Search.appendIndex(
    [
                {
            "fqsen": "\\Comentario",
            "name": "Comentario",
            "summary": "",
            "url": "classes/Comentario.html"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetIdComentario\u0028\u0029",
            "name": "getIdComentario",
            "summary": "",
            "url": "classes/Comentario.html#method_getIdComentario"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetIdTarea\u0028\u0029",
            "name": "getIdTarea",
            "summary": "",
            "url": "classes/Comentario.html#method_getIdTarea"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetIdUsuario\u0028\u0029",
            "name": "getIdUsuario",
            "summary": "",
            "url": "classes/Comentario.html#method_getIdUsuario"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetContenido\u0028\u0029",
            "name": "getContenido",
            "summary": "",
            "url": "classes/Comentario.html#method_getContenido"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetFechaComentario\u0028\u0029",
            "name": "getFechaComentario",
            "summary": "",
            "url": "classes/Comentario.html#method_getFechaComentario"
        },                {
            "fqsen": "\\Comentario\u003A\u003AsetIdComentario\u0028\u0029",
            "name": "setIdComentario",
            "summary": "",
            "url": "classes/Comentario.html#method_setIdComentario"
        },                {
            "fqsen": "\\Comentario\u003A\u003AsetIdTarea\u0028\u0029",
            "name": "setIdTarea",
            "summary": "",
            "url": "classes/Comentario.html#method_setIdTarea"
        },                {
            "fqsen": "\\Comentario\u003A\u003AsetIdUsuario\u0028\u0029",
            "name": "setIdUsuario",
            "summary": "",
            "url": "classes/Comentario.html#method_setIdUsuario"
        },                {
            "fqsen": "\\Comentario\u003A\u003AsetContenido\u0028\u0029",
            "name": "setContenido",
            "summary": "",
            "url": "classes/Comentario.html#method_setContenido"
        },                {
            "fqsen": "\\Comentario\u003A\u003AsetFechaComentario\u0028\u0029",
            "name": "setFechaComentario",
            "summary": "",
            "url": "classes/Comentario.html#method_setFechaComentario"
        },                {
            "fqsen": "\\Comentario\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Comentario.html#method_create"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetComentarioById\u0028\u0029",
            "name": "getComentarioById",
            "summary": "",
            "url": "classes/Comentario.html#method_getComentarioById"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetAllComentarios\u0028\u0029",
            "name": "getAllComentarios",
            "summary": "",
            "url": "classes/Comentario.html#method_getAllComentarios"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetByUser\u0028\u0029",
            "name": "getByUser",
            "summary": "",
            "url": "classes/Comentario.html#method_getByUser"
        },                {
            "fqsen": "\\Comentario\u003A\u003AgetByTarea\u0028\u0029",
            "name": "getByTarea",
            "summary": "",
            "url": "classes/Comentario.html#method_getByTarea"
        },                {
            "fqsen": "\\Comentario\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Comentario.html#method_update"
        },                {
            "fqsen": "\\Comentario\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Comentario.html#method_delete"
        },                {
            "fqsen": "\\Comentario\u003A\u003A\u0024id_comentario",
            "name": "id_comentario",
            "summary": "",
            "url": "classes/Comentario.html#property_id_comentario"
        },                {
            "fqsen": "\\Comentario\u003A\u003A\u0024id_tarea",
            "name": "id_tarea",
            "summary": "",
            "url": "classes/Comentario.html#property_id_tarea"
        },                {
            "fqsen": "\\Comentario\u003A\u003A\u0024id_usuario",
            "name": "id_usuario",
            "summary": "",
            "url": "classes/Comentario.html#property_id_usuario"
        },                {
            "fqsen": "\\Comentario\u003A\u003A\u0024contenido",
            "name": "contenido",
            "summary": "",
            "url": "classes/Comentario.html#property_contenido"
        },                {
            "fqsen": "\\Comentario\u003A\u003A\u0024fecha_comentario",
            "name": "fecha_comentario",
            "summary": "",
            "url": "classes/Comentario.html#property_fecha_comentario"
        },                {
            "fqsen": "\\Compartidas",
            "name": "Compartidas",
            "summary": "",
            "url": "classes/Compartidas.html"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetIdCompartidas\u0028\u0029",
            "name": "getIdCompartidas",
            "summary": "",
            "url": "classes/Compartidas.html#method_getIdCompartidas"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetIdTarea\u0028\u0029",
            "name": "getIdTarea",
            "summary": "",
            "url": "classes/Compartidas.html#method_getIdTarea"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetUsuario_Origen\u0028\u0029",
            "name": "getUsuario_Origen",
            "summary": "",
            "url": "classes/Compartidas.html#method_getUsuario_Origen"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetUsuario_Destino\u0028\u0029",
            "name": "getUsuario_Destino",
            "summary": "",
            "url": "classes/Compartidas.html#method_getUsuario_Destino"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetPermiso\u0028\u0029",
            "name": "getPermiso",
            "summary": "",
            "url": "classes/Compartidas.html#method_getPermiso"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetFechaCompartida\u0028\u0029",
            "name": "getFechaCompartida",
            "summary": "",
            "url": "classes/Compartidas.html#method_getFechaCompartida"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetIdCompartidas\u0028\u0029",
            "name": "setIdCompartidas",
            "summary": "",
            "url": "classes/Compartidas.html#method_setIdCompartidas"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetIdTarea\u0028\u0029",
            "name": "setIdTarea",
            "summary": "",
            "url": "classes/Compartidas.html#method_setIdTarea"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetUsuario_Origen\u0028\u0029",
            "name": "setUsuario_Origen",
            "summary": "",
            "url": "classes/Compartidas.html#method_setUsuario_Origen"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetUsuario_Destino\u0028\u0029",
            "name": "setUsuario_Destino",
            "summary": "",
            "url": "classes/Compartidas.html#method_setUsuario_Destino"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetPermiso\u0028\u0029",
            "name": "setPermiso",
            "summary": "",
            "url": "classes/Compartidas.html#method_setPermiso"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AsetFechaCompartida\u0028\u0029",
            "name": "setFechaCompartida",
            "summary": "",
            "url": "classes/Compartidas.html#method_setFechaCompartida"
        },                {
            "fqsen": "\\Compartidas\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Compartidas.html#method_create"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetCompartidasById\u0028\u0029",
            "name": "getCompartidasById",
            "summary": "",
            "url": "classes/Compartidas.html#method_getCompartidasById"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetAllCompartidas\u0028\u0029",
            "name": "getAllCompartidas",
            "summary": "",
            "url": "classes/Compartidas.html#method_getAllCompartidas"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetByTarea\u0028\u0029",
            "name": "getByTarea",
            "summary": "",
            "url": "classes/Compartidas.html#method_getByTarea"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetByUser\u0028\u0029",
            "name": "getByUser",
            "summary": "",
            "url": "classes/Compartidas.html#method_getByUser"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetByUserDestino\u0028\u0029",
            "name": "getByUserDestino",
            "summary": "",
            "url": "classes/Compartidas.html#method_getByUserDestino"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AgetCompartidasByTareaAndUser\u0028\u0029",
            "name": "getCompartidasByTareaAndUser",
            "summary": "",
            "url": "classes/Compartidas.html#method_getCompartidasByTareaAndUser"
        },                {
            "fqsen": "\\Compartidas\u003A\u003AupdatePermiso\u0028\u0029",
            "name": "updatePermiso",
            "summary": "",
            "url": "classes/Compartidas.html#method_updatePermiso"
        },                {
            "fqsen": "\\Compartidas\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Compartidas.html#method_update"
        },                {
            "fqsen": "\\Compartidas\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Compartidas.html#method_delete"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024id_compartidas",
            "name": "id_compartidas",
            "summary": "",
            "url": "classes/Compartidas.html#property_id_compartidas"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024id_tarea",
            "name": "id_tarea",
            "summary": "",
            "url": "classes/Compartidas.html#property_id_tarea"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024id_usuario_origen",
            "name": "id_usuario_origen",
            "summary": "",
            "url": "classes/Compartidas.html#property_id_usuario_origen"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024id_usuario_destino",
            "name": "id_usuario_destino",
            "summary": "",
            "url": "classes/Compartidas.html#property_id_usuario_destino"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024permiso",
            "name": "permiso",
            "summary": "",
            "url": "classes/Compartidas.html#property_permiso"
        },                {
            "fqsen": "\\Compartidas\u003A\u003A\u0024fecha_compartida",
            "name": "fecha_compartida",
            "summary": "",
            "url": "classes/Compartidas.html#property_fecha_compartida"
        },                {
            "fqsen": "\\Subtarea",
            "name": "Subtarea",
            "summary": "",
            "url": "classes/Subtarea.html"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetIdSubtarea\u0028\u0029",
            "name": "getIdSubtarea",
            "summary": "",
            "url": "classes/Subtarea.html#method_getIdSubtarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetIdTarea\u0028\u0029",
            "name": "getIdTarea",
            "summary": "",
            "url": "classes/Subtarea.html#method_getIdTarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetDescripcion\u0028\u0029",
            "name": "getDescripcion",
            "summary": "",
            "url": "classes/Subtarea.html#method_getDescripcion"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetCompletado\u0028\u0029",
            "name": "getCompletado",
            "summary": "",
            "url": "classes/Subtarea.html#method_getCompletado"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AsetIdSubtarea\u0028\u0029",
            "name": "setIdSubtarea",
            "summary": "",
            "url": "classes/Subtarea.html#method_setIdSubtarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AsetIdTarea\u0028\u0029",
            "name": "setIdTarea",
            "summary": "",
            "url": "classes/Subtarea.html#method_setIdTarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AsetDescripcion\u0028\u0029",
            "name": "setDescripcion",
            "summary": "",
            "url": "classes/Subtarea.html#method_setDescripcion"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AsetCompletado\u0028\u0029",
            "name": "setCompletado",
            "summary": "",
            "url": "classes/Subtarea.html#method_setCompletado"
        },                {
            "fqsen": "\\Subtarea\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Subtarea.html#method_create"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetSubtareaById\u0028\u0029",
            "name": "getSubtareaById",
            "summary": "",
            "url": "classes/Subtarea.html#method_getSubtareaById"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetAllSubtareas\u0028\u0029",
            "name": "getAllSubtareas",
            "summary": "",
            "url": "classes/Subtarea.html#method_getAllSubtareas"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AupdateDescripcion\u0028\u0029",
            "name": "updateDescripcion",
            "summary": "",
            "url": "classes/Subtarea.html#method_updateDescripcion"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AupdateCompletado\u0028\u0029",
            "name": "updateCompletado",
            "summary": "",
            "url": "classes/Subtarea.html#method_updateCompletado"
        },                {
            "fqsen": "\\Subtarea\u003A\u003AgetSubtareasByTarea\u0028\u0029",
            "name": "getSubtareasByTarea",
            "summary": "",
            "url": "classes/Subtarea.html#method_getSubtareasByTarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Subtarea.html#method_update"
        },                {
            "fqsen": "\\Subtarea\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Subtarea.html#method_delete"
        },                {
            "fqsen": "\\Subtarea\u003A\u003A\u0024id_subtarea",
            "name": "id_subtarea",
            "summary": "",
            "url": "classes/Subtarea.html#property_id_subtarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003A\u0024id_tarea",
            "name": "id_tarea",
            "summary": "",
            "url": "classes/Subtarea.html#property_id_tarea"
        },                {
            "fqsen": "\\Subtarea\u003A\u003A\u0024descripcion",
            "name": "descripcion",
            "summary": "",
            "url": "classes/Subtarea.html#property_descripcion"
        },                {
            "fqsen": "\\Subtarea\u003A\u003A\u0024completado",
            "name": "completado",
            "summary": "",
            "url": "classes/Subtarea.html#property_completado"
        },                {
            "fqsen": "\\Tarea",
            "name": "Tarea",
            "summary": "",
            "url": "classes/Tarea.html"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetIdTarea\u0028\u0029",
            "name": "getIdTarea",
            "summary": "",
            "url": "classes/Tarea.html#method_getIdTarea"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetIdUsuario\u0028\u0029",
            "name": "getIdUsuario",
            "summary": "",
            "url": "classes/Tarea.html#method_getIdUsuario"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetTitulo\u0028\u0029",
            "name": "getTitulo",
            "summary": "",
            "url": "classes/Tarea.html#method_getTitulo"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetFechaCreacion\u0028\u0029",
            "name": "getFechaCreacion",
            "summary": "",
            "url": "classes/Tarea.html#method_getFechaCreacion"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetFechaLimite\u0028\u0029",
            "name": "getFechaLimite",
            "summary": "",
            "url": "classes/Tarea.html#method_getFechaLimite"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetPrioridad\u0028\u0029",
            "name": "getPrioridad",
            "summary": "",
            "url": "classes/Tarea.html#method_getPrioridad"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetEstado\u0028\u0029",
            "name": "getEstado",
            "summary": "",
            "url": "classes/Tarea.html#method_getEstado"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetDescripcion\u0028\u0029",
            "name": "getDescripcion",
            "summary": "",
            "url": "classes/Tarea.html#method_getDescripcion"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetIdTarea\u0028\u0029",
            "name": "setIdTarea",
            "summary": "",
            "url": "classes/Tarea.html#method_setIdTarea"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetIdUsuario\u0028\u0029",
            "name": "setIdUsuario",
            "summary": "",
            "url": "classes/Tarea.html#method_setIdUsuario"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetTitulo\u0028\u0029",
            "name": "setTitulo",
            "summary": "",
            "url": "classes/Tarea.html#method_setTitulo"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetFechaCreacion\u0028\u0029",
            "name": "setFechaCreacion",
            "summary": "",
            "url": "classes/Tarea.html#method_setFechaCreacion"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetFechaLimite\u0028\u0029",
            "name": "setFechaLimite",
            "summary": "",
            "url": "classes/Tarea.html#method_setFechaLimite"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetPrioridad\u0028\u0029",
            "name": "setPrioridad",
            "summary": "",
            "url": "classes/Tarea.html#method_setPrioridad"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetEstado\u0028\u0029",
            "name": "setEstado",
            "summary": "",
            "url": "classes/Tarea.html#method_setEstado"
        },                {
            "fqsen": "\\Tarea\u003A\u003AsetDescripcion\u0028\u0029",
            "name": "setDescripcion",
            "summary": "",
            "url": "classes/Tarea.html#method_setDescripcion"
        },                {
            "fqsen": "\\Tarea\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Tarea.html#method_create"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetAllTareas\u0028\u0029",
            "name": "getAllTareas",
            "summary": "",
            "url": "classes/Tarea.html#method_getAllTareas"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetTareaById\u0028\u0029",
            "name": "getTareaById",
            "summary": "",
            "url": "classes/Tarea.html#method_getTareaById"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetTareasByUser\u0028\u0029",
            "name": "getTareasByUser",
            "summary": "",
            "url": "classes/Tarea.html#method_getTareasByUser"
        },                {
            "fqsen": "\\Tarea\u003A\u003AupdateDescripcion\u0028\u0029",
            "name": "updateDescripcion",
            "summary": "",
            "url": "classes/Tarea.html#method_updateDescripcion"
        },                {
            "fqsen": "\\Tarea\u003A\u003AupdateTitulo\u0028\u0029",
            "name": "updateTitulo",
            "summary": "",
            "url": "classes/Tarea.html#method_updateTitulo"
        },                {
            "fqsen": "\\Tarea\u003A\u003AupdatePrioridad\u0028\u0029",
            "name": "updatePrioridad",
            "summary": "",
            "url": "classes/Tarea.html#method_updatePrioridad"
        },                {
            "fqsen": "\\Tarea\u003A\u003AupdateEstado\u0028\u0029",
            "name": "updateEstado",
            "summary": "",
            "url": "classes/Tarea.html#method_updateEstado"
        },                {
            "fqsen": "\\Tarea\u003A\u003AupdateFechaLimite\u0028\u0029",
            "name": "updateFechaLimite",
            "summary": "",
            "url": "classes/Tarea.html#method_updateFechaLimite"
        },                {
            "fqsen": "\\Tarea\u003A\u003AgetTareasUrgentes\u0028\u0029",
            "name": "getTareasUrgentes",
            "summary": "",
            "url": "classes/Tarea.html#method_getTareasUrgentes"
        },                {
            "fqsen": "\\Tarea\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "",
            "url": "classes/Tarea.html#method_update"
        },                {
            "fqsen": "\\Tarea\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Tarea.html#method_delete"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024id_tarea",
            "name": "id_tarea",
            "summary": "",
            "url": "classes/Tarea.html#property_id_tarea"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024id_usuario",
            "name": "id_usuario",
            "summary": "",
            "url": "classes/Tarea.html#property_id_usuario"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024titulo",
            "name": "titulo",
            "summary": "",
            "url": "classes/Tarea.html#property_titulo"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024fecha_creacion",
            "name": "fecha_creacion",
            "summary": "",
            "url": "classes/Tarea.html#property_fecha_creacion"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024fecha_limite",
            "name": "fecha_limite",
            "summary": "",
            "url": "classes/Tarea.html#property_fecha_limite"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024prioridad",
            "name": "prioridad",
            "summary": "",
            "url": "classes/Tarea.html#property_prioridad"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024estado",
            "name": "estado",
            "summary": "",
            "url": "classes/Tarea.html#property_estado"
        },                {
            "fqsen": "\\Tarea\u003A\u003A\u0024descripcion",
            "name": "descripcion",
            "summary": "",
            "url": "classes/Tarea.html#property_descripcion"
        },                {
            "fqsen": "\\Usuario",
            "name": "Usuario",
            "summary": "Clase\u0020que\u0020representa\u0020un\u0020usuario\u0020en\u0020el\u0020sistema",
            "url": "classes/Usuario.html"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetIdUsuario\u0028\u0029",
            "name": "getIdUsuario",
            "summary": "Obtiene\u0020el\u0020ID\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getIdUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetNombre\u0028\u0029",
            "name": "getNombre",
            "summary": "Obtiene\u0020el\u0020nombre\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getNombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "Obtiene\u0020el\u0020email\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getEmail"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetContrase\u00F1a\u0028\u0029",
            "name": "getContrase\u00F1a",
            "summary": "Obtiene\u0020la\u0020contrasela\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getContrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetFechaRegistro\u0028\u0029",
            "name": "getFechaRegistro",
            "summary": "Obtiene\u0020la\u0020fecha\u0020de\u0020registro\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getFechaRegistro"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetImagen\u0028\u0029",
            "name": "getImagen",
            "summary": "Obtiene\u0020la\u0020imagen\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_getImagen"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetIdUsuario\u0028\u0029",
            "name": "setIdUsuario",
            "summary": "Establece\u0020la\u0020ID\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setIdUsuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetNombre\u0028\u0029",
            "name": "setNombre",
            "summary": "Establece\u0020el\u0020nombre\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setNombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "Establece\u0020el\u0020email\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setEmail"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetContrase\u00F1a\u0028\u0029",
            "name": "setContrase\u00F1a",
            "summary": "Establece\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setContrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetFechaRegistro\u0028\u0029",
            "name": "setFechaRegistro",
            "summary": "Establece\u0020la\u0020fecha\u0020de\u0020registro\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setFechaRegistro"
        },                {
            "fqsen": "\\Usuario\u003A\u003AsetImagen\u0028\u0029",
            "name": "setImagen",
            "summary": "Establece\u0020la\u0020imagen\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_setImagen"
        },                {
            "fqsen": "\\Usuario\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Crea\u0020un\u0020nuevo\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_create"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetAllUsers\u0028\u0029",
            "name": "getAllUsers",
            "summary": "Obtiene\u0020todos\u0020los\u0020usuarios\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_getAllUsers"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetUserByName\u0028\u0029",
            "name": "getUserByName",
            "summary": "Obtiene\u0020un\u0020usuario\u0020por\u0020su\u0020nombre",
            "url": "classes/Usuario.html#method_getUserByName"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetUserByEmail\u0028\u0029",
            "name": "getUserByEmail",
            "summary": "Obtiene\u0020un\u0020usuario\u0020por\u0020su\u0020email",
            "url": "classes/Usuario.html#method_getUserByEmail"
        },                {
            "fqsen": "\\Usuario\u003A\u003AgetUserById\u0028\u0029",
            "name": "getUserById",
            "summary": "Obtiene\u0020un\u0020usuario\u0020por\u0020su\u0020ID",
            "url": "classes/Usuario.html#method_getUserById"
        },                {
            "fqsen": "\\Usuario\u003A\u003AverifyPassword\u0028\u0029",
            "name": "verifyPassword",
            "summary": "Verifica\u0020si\u0020las\u0020credenciales\u0020del\u0020usuario\u0020son\u0020v\u00E1lidas",
            "url": "classes/Usuario.html#method_verifyPassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003AupdatePassword\u0028\u0029",
            "name": "updatePassword",
            "summary": "Actualiza\u0020la\u0020contrase\u00F1a\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_updatePassword"
        },                {
            "fqsen": "\\Usuario\u003A\u003Aupdate\u0028\u0029",
            "name": "update",
            "summary": "Actualiza\u0020los\u0020datos\u0020del\u0020usuario",
            "url": "classes/Usuario.html#method_update"
        },                {
            "fqsen": "\\Usuario\u003A\u003AEmailExiste\u0028\u0029",
            "name": "EmailExiste",
            "summary": "Verifica\u0020si\u0020el\u0020email\u0020del\u0020usuario\u0020ya\u0020existe",
            "url": "classes/Usuario.html#method_EmailExiste"
        },                {
            "fqsen": "\\Usuario\u003A\u003AUsuarioExiste\u0028\u0029",
            "name": "UsuarioExiste",
            "summary": "Verifica\u0020si\u0020el\u0020nombre\u0020de\u0020usuario\u0020ya\u0020existe",
            "url": "classes/Usuario.html#method_UsuarioExiste"
        },                {
            "fqsen": "\\Usuario\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Elimina\u0020el\u0020usuario\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Usuario.html#method_delete"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024id_usuario",
            "name": "id_usuario",
            "summary": "",
            "url": "classes/Usuario.html#property_id_usuario"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024nombre",
            "name": "nombre",
            "summary": "",
            "url": "classes/Usuario.html#property_nombre"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024email",
            "name": "email",
            "summary": "",
            "url": "classes/Usuario.html#property_email"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024contrase\u00F1a",
            "name": "contrase\u00F1a",
            "summary": "",
            "url": "classes/Usuario.html#property_contrase%C3%B1a"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024fecha_registro",
            "name": "fecha_registro",
            "summary": "",
            "url": "classes/Usuario.html#property_fecha_registro"
        },                {
            "fqsen": "\\Usuario\u003A\u003A\u0024imagen",
            "name": "imagen",
            "summary": "",
            "url": "classes/Usuario.html#property_imagen"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
